const data = {
    events:[
        {
            _id:'1',
            name:'Curso de Ingles',
            category:'Idiomas',
            image:'/images/p1.jpg',
            description:'Curso de ingles semanal',
            date:'30/08/2021',
            campus:'IFSP-Itapetininga',
        },
        {
            _id:'2',
            name:'Curso de programação',
            category:'Tecnologia da Informacao',
            image:'/images/p2.jpg',
            description:'Curso de programação em python',
            date:'10/08/2021',
            campus:'FATEC-Itapetininga',
        },
        {
            _id:'3',
            name:'Semana da contabilidade',
            category:'Administracao e Empreendedorismo',
            image:'/images/p3.jpg',
            description:'Semana com palestras sobre termos contabeis,Semana com palestras sobre termos contabeis,Semana com palestras sobre termos contabeis,Semana com palestras sobre termos contabeis',
            date:'15/08/2021',
            campus:'FKB-Itapetininga',
        },
        {
            _id:'4',
            name:'Semana da Tecnologia',
            category:'Tecnologia da Informacao',
            image:'/images/p4.jpg',
            description:'Duas semanas repletas de conteudos desenvolvidos para area de t.i',
            date:'10/08/2021',
            campus:'IFSP-Itapetininga',
        },
        {
            _id:'5',
            name:'Semana IBM',
            category:'Tecnologia da Informacao',
            image:'/images/p1.jpg',
            description:'Curso com as principais ferramentas da IBM',
            date:'10/08/2021',
            campus:'FATEC-Itapetininga',
        },
        {
            _id:'6',
            name:'Cuidados no ambiente de trabalho',
            category:'Saude e Seguranca',
            image:'/images/p1.jpg',
            description:'Curso de ingles semanal',
            date:'10/08/2021',
            campus:'ETEC-Itapetininga',
        },
    ],
};
export default data